travis up
start-jsk/rtmros_tutorials pull request #592
Opened 2021-04-24 07:58 UTC by Naoki-Hiraoka

テストで次のようなエラーが出ました。
```
++ curl https://bootstrap.pypa.io/2.7/get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   936  100   936    0     0   5427      0 --:--:-- --:--:-- --:--:--  5441
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
    https://bootstrap.pypa.io/pip/2.7/get-pip.py
```
https://github.com/jsk-ros-pkg/jsk_travis/pull/416
https://github.com/jsk-ros-pkg/jsk_travis/pull/414
によって直ると思われるため、jsk_travisを最新のものを使用するようにしました。

2021-05-30 05:05 UTC, Naoki-Hiraoka commented
[jsk_control](https://github.com/jsk-ros-pkg/jsk_control/actions)を真似して、kinetic と melodic を Github Action でテストする形にしました。テスト結果は
https://github.com/Naoki-Hiraoka/rtmros_tutorials/actions/runs/889505232
https://github.com/Naoki-Hiraoka/rtmros_tutorials/actions/runs/889505231
にあります。

@k-okada よろしければ、githubのchecks設定の変更とmergeをお願いいたします。

2021-06-02 04:56 UTC, Naoki-Hiraoka commented
indigoを加えました．テスト結果は https://github.com/Naoki-Hiraoka/rtmros_tutorials/actions/runs/898166895 にあります．

2021-06-02 13:20 UTC, k-okada requested changes
please update  .travis.yml too, like https://github.com/jsk-ros-pkg/jsk_control/commit/b1f1ef78d9035a369020a48b6dc8ee6f65652556

2021-06-03 03:20 UTC, Naoki-Hiraoka commented
I think I have already updated.

2021-06-03 03:51 UTC, k-okada commented
I see, wait for https://travis-ci.com/github/start-jsk/rtmros_tutorials/pull_requests

2021-06-05 05:45 UTC, k-okada approved these changes
finally, travis passed https://travis-ci.com/github/start-jsk/rtmros_tutorials/builds/227809649

2021-06-05 05:45 UTC, merged